//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GMFConvert.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GMFCONTYPE                  129
#define IDB_STATUS                      130
#define IDB_STATUS_SMALL                131
#define IDB_HEADERSORT_SMALL            132
#define IDD_OPTIONS                     133
#define IDD_CONFIGURE_FILE              134
#define IDD_CONFIGURE_AUDIO             135
#define IDD_CONFIGURE_VIDEO             136
#define IDB_FILENAME_BROWSE             137
#define IDB_FOLDER_BROWSE               138
#define IDC_DURATION_ADD                1000
#define IDC_RECURSIVE_ADDDIR            1001
#define IDC_DEFAULTS                    1002
#define IDC_OUTPUT_FOLDER_SAME          1004
#define IDC_OUTPUT_FOLDER_USE           1005
#define IDC_OUTPUT_FOLDER_EDIT          1006
#define IDC_OUTPUT_FOLDER_BROWSE        1007
#define IDC_OUTPUT_FILENAME_SAME        1008
#define IDC_AUDIO_FILTERS               1008
#define IDC_OUTPUT_FILENAME_USE         1009
#define IDC_AUDIO_FORMATS               1009
#define IDC_OUTPUT_FILENAME_EDIT        1010
#define IDC_OUTPUT_FILENAME_BROWSE      1011
#define IDC_OUTPUT_FILETYPE_AVI         1012
#define IDC_OUTPUT_FILETYPE_WAV         1014
#define IDC_OUTPUT_FILETYPE_EXT_EDIT    1016
#define IDC_VCM_CONFIGURE               1017
#define IDC_VCM_ABOUT                   1018
#define IDC_VIDEO_BITRATE_EDIT          1020
#define IDC_VIDEO_QUALITY_SLIDER        1021
#define IDC_VIDEO_QUALITY_EDIT          1022
#define IDC_VIDEO_KEYFRAME_EDIT         1023
#define IDC_VIDEO_PFRAME_EDIT           1024
#define IDC_VIDEO_WINDOWSIZE_EDIT       1025
#define IDC_VIDEO_WINDOWSIZE_CHECK      1027
#define IDC_VIDEO_PFRAME_CHECK          1028
#define IDC_VIDEO_KEYFRAME_CHECK        1029
#define IDC_VIDEO_QUALITY_CHECK         1030
#define IDC_VIDEO_BITRATE_CHECK         1031
#define IDC_VIDEO_FILTERS               1032
#define IDC_AUDIO_FORMAT_TAG            1038
#define IDC_BLOCK_ALIGN                 1039
#define IDC_DATA_RATE                   1040
#define IDC_VIDEO_BITRATE_UNITS         1041
#define IDC_AUDIO_FORMAT_DESC           1041
#define IDC_VIDEO_QUALITY_UNITS         1044
#define IDC_INTERLEAVING_MODE_NONE      1045
#define IDC_INTERLEAVING_MODE_CAPTURE   1046
#define IDC_INTERLEAVING_MODE_FULL      1047
#define IDC_INTERLEAVING_FREQUENCY      1049
#define IDC_INTERLEAVING_PREROLL        1050
#define IDC_AVI_MUX_MASTER_CHECK        1051
#define IDC_AVI_MUX_MASTER_EDIT         1052
#define IDC_AVI_MUX_INDEX               1053
#define IDC_STATIC_AVI_MUX_SETTINGS     1054
#define IDC_STATIC_INTERLEAVING_MODE    1055
#define IDC_STATIC_INTERLEAVING_PARAMS  1056
#define IDC_STATIC_INTERLEAVING_FREQUENCY 1057
#define IDC_STATIC_INTERLEAVING_PREROLL 1058
#define IDC_STATIC_AVI_SPECIFIC_SETTINGS 1059
#define IDC_STATIC_VIDEO_FILTERS        1060
#define IDC_STATIC_VIDEO_SETTINGS       1062
#define ID_CLEAR_LIST                   32771
#define ID_ADD_FILE                     32775
#define ID_ADD_DIR                      32776
#define ID_SELECT_ALL                   32777
#define ID_INVERT_SEL                   32778
#define ID_RUN_CONVERT                  32781
#define ID_PAUSE_CONVERT                32782
#define ID_STOP_CONVERT                 32783
#define ID_UNSELECT_ALL                 32791
#define ID_CONFIG_CONVERT               32797
#define ID_OPTIONS                      32804
#define IDS_FAILED                      61204
#define IDS_SUCCEEDED                   61205
#define IDS_RUNNING                     61206
#define IDS_WAITING                     61207
#define IDS_PAUSED                      61208
#define IDS_STOPPED                     61209
#define IDS_PERCENTAGE                  61210
#define IDS_POSITION                    61211
#define IDS_COM_INIT_FAILED             61212
#define IDS_REG_KEY                     61213
#define IDS_OPTION_DURATION_ADD         61214
#define IDS_BROWSE_DIR_ADD              61215
#define IDS_OPTION_RECURSIVE_ADDDIR     61216
#define IDS_CONFIGURE_TITLE             61217
#define IDS_BROWSE_DIR_DEST             61218
#define IDS_FILTER_NO_PROPERTY_BAG      61219
#define IDS_FILTER_NO_FRIENDLY_NAME     61220
#define IDS_AUDIO_NULL_FILTER           61222
#define IDS_VIDEO_NULL_FILTER           61223
#define IDS_FILTER_NO_OBJECT            61224
#define IDS_FILTER_NO_PIN_ENUM          61225
#define IDS_FILTER_NO_CONFIG            61226
#define IDS_FILTER_NO_CAPS              61227
#define IDS_AUDIO_RAW_FILTER            61228
#define IDS_VIDEO_RAW_FILTER            61229
#define IDS_AUDIO_NULL_FILTER_DESC      61230
#define IDS_VIDEO_NULL_FILTER_DESC      61231
#define IDS_AUDIO_RAW_FILTER_DESC       61232
#define IDS_VIDEO_RAW_FILTER_DESC       61233
#define IDS_FORMAT_UNEXPECTED_MEDIA_TYPE 61234
#define IDS_FORMAT_UNEXPECTED_FORMAT_TYPE 61235

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
